name: shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  uses-material-design: true
  assets:
    - assets/catcrochet_logo.png
    # TODO: Add slanted menu asset (104)
    - assets/crochet/duck_with_hat.jpeg
    - assets/crochet/flower_bunny.jpeg
    - assets/crochet/little_hammie.jpeg
    - assets/crochet/fat_raccoon.jpeg
    - assets/crochet/pochacco.jpeg
    - assets/crochet/elephant.jpeg
    - assets/crochet/toothless_lightfury.jpeg
    - assets/crochet/bee.jpeg
    - assets/crochet/nemo.jpeg
    - assets/crochet/cloud.jpeg
    - assets/crochet/pug.jpeg
    - assets/crochet/pig.jpeg
    - assets/crochet/giraffe.jpeg
    - assets/crochet/cappy.jpeg
    - assets/crochet/mushroom_bunny.jpeg
    - assets/crochet/smol_cat.jpeg
    - assets/crochet/corgi.jpeg
    - assets/crochet/sheep.jpeg
    - assets/crochet/cool_teddy.jpeg
    - assets/crochet/cozy_penguin.jpeg
    - assets/crochet/pompompurin.jpeg
    - assets/crochet/mammoth.jpeg
    - assets/crochet/strawberry_turtle.jpeg
    - assets/crochet/otter.jpeg
    - assets/crochet/rat.jpeg
    - assets/crochet/whale.jpeg
    - assets/crochet/axolotl.jpeg
    - assets/crochet/perry.jpeg
    - assets/crochet/totoro.jpeg
    - assets/crochet/octopus.jpeg
    - assets/crochet/barebear.jpeg
    - assets/crochet/monkey.jpeg
    - assets/crochet/cow.jpeg
    - assets/crochet/mushroom.jpeg
    - assets/crochet/hammerhead.jpeg
    - assets/crochet/minion.jpeg
    - assets/crochet/donald_duck.jpeg

